kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redb-role
  labels:
    app: redis-enterprise
subjects:
- kind: ServiceAccount
  name: redis-enterprise-operator
  namespace: {{ .Values.rec_namespace  }} 
- kind: ServiceAccount
  name: <service-account-name>
  namespace: {{ .Values.rec_namespace }} 
roleRef:
  kind: Role
  name: redb-role
  apiGroup: rbac.authorization.k8s.io
