apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: db-2
spec:
  memorySize: {{ .Values.memorySize }}
  databasePort: {{ .Values.databasePort }}
  shardCount: {{ .Values.shardCount }}
  replication: true
  tlsMode: enabled
  rolesPermissions:
    - acl: "Full Access"
      type: "redis-enterprise"
      role: "DB Viewer"
