apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-acl-config
data:
  config.txt: |
    # Create an ACL for key prefix abc
    curl -k -u "$USERNAME:$PASSWORD" -X POST \
    -H 'Content-Type: application/json' \
    -d '{ "name": "abc-acl", "acl": "~abc* +@all -@dangerous" }' \
    https://{{ .Values.recname  }}:9443/v1/redis_acls

    # Create abc-role
    curl -k -u "$USERNAME:$PASSWORD" -X POST \
    -H 'Content-Type: application/json' \
    -d '{"management":"none","name":"abc-role"}' \
    https://{{ .Values.recname  }}:9443/v1/roles

    #
    curl -k -u "$USERNAME:$PASSWORD" -X POST   \
    -H 'Content-Type: application/json' -d '{ "email": "newuser@example.com", "password": "1234", "name": "abc-user", "role_uids": [ 2 ], "auth_method": "regular" }' \
    https://rec-prod:9443/v1/users
