apiVersion: batch/v1
kind: Job
metadata:
  name: patch-configmap
  namespace:  {{ .Values.recNamespace  }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      serviceAccount: redis-enterprise-operator
      containers:
        - name: patch
          image: bitnami/kubectl:latest
          command:
            - "/bin/bash"
            - "-c"
            - >
              kubectl patch ConfigMap/operator-environment-config --type merge -p '{"data": {"REDB_NAMESPACES": "{{ .Values.ManagedNameSpace }}"}}'
      restartPolicy: Never
  backoffLimit: 1
