apiVersion: batch/v1
kind: Job
metadata:
  name: patch-configmap
  namespace: {{ .Values.recNamespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: patch
          image: bitnami/kubectl:latest
          command: ["/bin/sh"]
          args: ["-c", "kubectl patch ConfigMap/operator-environment-config -n prod   --type merge -p '{"data":{"REDB_NAMESPACES": "dev,stg"}}' "] 
      restartPolicy: Never
  backoffLimit: 1
