apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: "{{ .Values.recname }}"
spec:
  nodes: "{{ .Values.nodes }}"
  redisEnterpriseImageSpec:
    repository: "{{ .Values.repository }}" 
    versionTag: "{{ .Values.versionTag }}" 
  redisEnterpriseServicesRiggerImageSpec:
    repository: registry.connect.redhat.com/redislabs/services-manager
  bootstrapperImageSpec:
    repository: registry.connect.redhat.com/redislabs/redis-enterprise-operator
  persistentSpec:
    enabled: true
    volumeSize: "{{ .Values.volumeSize }}"
  redisEnterpriseNodeResources:
    limits:
      cpu: "{{ .Values.limits.cpu }}"
      memory: "{{ .Values.limits.memory }}"
    requests:
      cpu: "{{ .Values.requests.cpu }}"
      memory: "{{ .Values.requests.memory }}"
  username: {{ .Values.username }}
  nodes: {{ .Values.nodes }}
