apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: "{{ .Values.recname }}"
spec:
  nodes: "{{ .Values.nodes }}"
  redisEnterpriseImageSpec:
    repository: "{{ .Values.redisEnterpriseImageSpec }}" 
    versionTag: "{{ .Values.versionTag }}" 
  redisEnterpriseServicesRiggerImageSpec:
    repository: "{{ .Values.redisEnterpriseServicesRiggerImageSpec }}" 
    versionTag: "{{ .Values.versionTag }}" 
  bootstrapperImageSpec:
    repository: "{{ .Values.bootstrapperImageSpec }}" 
    versionTag: "{{ .Values.versionTag }}" 
  persistentSpec:
    enabled: true
    volumeSize: "{{ .Values.volumeSize }}"
  redisEnterpriseNodeResources:
    limits:
      cpu: "{{ .Values.limits.cpu }}"
      memory: "{{ .Values.limits.memory }}"
    requests:
      cpu: "{{ .Values.requests.cpu }}"
      memory: "{{ .Values.requests.memory }}"
  username: {{ .Values.username }}
