apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-acl-config
data:
  config.txt: |
    curl -k -u "$USERNAME:$PASSWORD" -X POST \
    -H 'Content-Type: application/json' \
    -d '{ "name": "abc-acl", "acl": "~abc* +@all -@dangerous" }' \
    https://rec:9443/v1/redis_acls

    
