apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  
  containers:
  - name: app
    image: rezarahim/alpine-tools:1.1
    command:
      - "/bin/sh"
      - "-c"
      - |
        count=0
        max=125
        while true; do
          curl -k -u "$USERNAME:$PASSWORD" https://rec:9443/v1/cluster
          if [ $? -eq 0 ]; then
            echo "Curl succeeded, breaking loop."
            break
          else
            echo "Curl failed, retrying in 5 seconds... ($count/$max)"
            sleep 10
          fi

          count=$((count + 1))
          if [ "$count" -ge "$max" ]; then
            echo "Reached max retries ($max), exiting loop."
            break
          fi
        done
        
        source /etc/config/config.txt
        sleep 3600
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: rec-prod
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: rec-prod
          key: password
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_SECRET_ACCESS_KEY
    - name: PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          name: rsa-keys
          key: private_key.pem
    - name: PUBLIC_KEY
      valueFrom:
        secretKeyRef:
          name: rsa-keys
          key: public_key.pem     
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: redis-acl-config
