---
apiVersion: v1
data:
  password: d0RERUlHQzA=
  username: ZGVtb0ByZWRpcy5jb20=
kind: Secret
metadata:
  name: redis-enterprise-rerc-north
type: Opaque

---

apiVersion: v1
data:
  password: OG5pcURvTWk=
  username: ZGVtb0ByZWRpcy5jb20=
kind: Secret
metadata:
  name: redis-enterprise-rerc-south
type: Opaque
