apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: {{ .Values.recname }}
  labels:
    app: redis-enterprise
  annotations:
    kubernetes.io/ingress.class: nginx 
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  # Add fields here
  nodes: {{ .Values.nodes }}
  persistentSpec:
    enabled: true
    volumeSize: {{ .Values.volumeSize }}
  redisEnterpriseNodeResources:
    limits:
      cpu: {{ .Values.limits.cpu }}
      memory: {{ .Values.limits.memory }}
    requests:
      cpu: {{ .Values.requests.cpu }}
      memory: {{ .Values.requests.memory }}
  username: {{ .Values.username }}
  redisEnterpriseImageSpec:
    repository: "{{ .Values.redisEnterpriseImageSpec }}"
    versionTag: "{{ .Values.versionTag }}"
  redisEnterpriseServicesRiggerImageSpec:
    repository: "{{ .Values.redisEnterpriseServicesRiggerImageSpec }}"  
  bootstrapperImageSpec:
    repository: "{{ .Values.bootstrapperImageSpec }}"
  activeActive:
    apiIngressUrl: {{ .Values.apiIngressUrl }}
    dbIngressSuffix:  {{ .Values.dbIngressSuffix }}
    method:  {{ .Values.method }}
