apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
  - name: app
    image: alpine/curl
    command: 
     - "/bin/sh"
     - "-c"
     - |
      while true; do
        curl -k -u "$USERNAME:$PASSWORD" https://rec:9443/v1/cluster
        if [ $? -eq 0 ]; then
          echo " Curl succeeded, breaking loop."
          break
        else
        echo "Curl failed, retrying in 5 seconds..."
         sleep 5
        fi
      done
      sleep 3600
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: rec
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: rec
          key: password
